version: '3'

services:
  ubuntu:
    container_name: dc.ubuntu
    build:
      context: ./.docker/ubuntu/
    volumes:
      - .:/var/www/html
      - ./.docker/logs:/var/log/apache2
      - ./.docker/.composer:/root/.composer
    ports:
      - 127.0.0.1:80:80
    links:
      - "db:db"

  db:
    container_name: dc.db
    build:
      context: ./.docker/db/
    environment:
      - "MYSQL_ROOT_PASSWORD=Password123"
    ports:
      - "3306:3306"
    volumes:
      - .docker/db/mounted_db:/var/www/db
      - ./.docker/.data/db:/var/lib/mysql:Z

## >> Delete for production!
  phpmyadmin:
    container_name: dc.phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      - "PMA_HOST=db"
      - "PMA_USER=root"
      - "PMA_PASSWORD=Password123"
    ports:
      - "8080:80"
    depends_on:
      - "db"
### <<<